service: fgl-middleware-order
runtime: java11

instance_class: F2

env_variables:
  SPRING_PROFILES_ACTIVE: dev

vpc_access_connector:
  name: projects/cerc-homolog/locations/us-east4/connectors/default-connector

